name: Deploy to AWS EKS

on:
  push:
    branches:
      - main
      - dev
      - staging

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Create ECR Repository
      run: |
        aws ecr describe-repositories --repository-names hello-kubernetes || \
        aws ecr create-repository --repository-name hello-kubernetes --region us-east-1

    - name: Login to Amazon ECR
      id: login-ecr
      run: |
        aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 195275643268.dkr.ecr.us-east-1.amazonaws.com

    - name: Build Docker Image
      run: |
        docker build -t hello-kubernetes .
        docker tag hello-kubernetes:latest 195275643268.dkr.ecr.us-east-1.amazonaws.com/hello-kubernetes:latest

    - name: Push Docker Image to Amazon ECR
      run: |
        docker push 195275643268.dkr.ecr.us-east-1.amazonaws.com/hello-kubernetes:latest
    
    - name: Set up kubectl to access EKS
      run: |
        aws eks --region us-east-1 update-kubeconfig --name your-cluster-name

    - name: Update Kubernetes Deployment
      run: |
        kubectl apply -f deployment.yaml
        kubectl apply -f service.yaml
        kubectl rollout restart deployment/hello-kubernetes
